//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINDPAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINDPALEntities5 : DbContext
    {
        public FINDPALEntities5()
            : base("name=FINDPALEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PostCategory> PostCategories { get; set; }
        public virtual DbSet<PostType> PostTypes { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ScanNotification> ScanNotifications { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
