//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINDPAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanNotification
    {
        public int NotificationId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> FinderUserId { get; set; }
        public Nullable<System.DateTime> ScanDateTime { get; set; }
        public bool IsContactShared { get; set; }
        public bool NotificationSent { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
